"""Lower the one-shape walkthrough kernel into an embeddable Hexagon TU."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import tilelang
from tilelang.utils.target import determine_target

from step1_tilelang_kernel import (
    K,
    M,
    N,
    NT,
    KT,
    PADDED_Q4_TILE_BYTES,
    make_compute_stage,
    make_dequant_stage,
    make_pack_stage,
)


BASE_SYMBOL = "tl_walkthrough_q4_m32_n256_k2048"
SYMBOLS = {
    "pack": f"{BASE_SYMBOL}_pack",
    "dequant": f"{BASE_SYMBOL}_dequant",
    "compute": f"{BASE_SYMBOL}_compute",
}


def lower(func, symbol: str) -> str:
    target = determine_target("hexagon", return_object=True)
    with target:
        artifact = tilelang.lower(
            func.with_attr("global_symbol", symbol),
            target=target,
            enable_host_codegen=False,
            enable_device_compile=False,
        )
    return str(artifact.kernel_source)


def generate(output_dir: Path) -> tuple[Path, Path]:
    kernels = [
        lower(make_pack_stage(), SYMBOLS["pack"]),
        lower(make_dequant_stage(), SYMBOLS["dequant"]),
        lower(make_compute_stage(), SYMBOLS["compute"]),
    ]
    source = (
        "// Generated by step2_generate.py. Do not hand-edit.\n"
        "#include <tl_templates/hexagon/tl_bridge.h>\n"
        "#define TL_Q4_0_PADDED_VTCM_INPUT 1\n"
        "#include <tl_templates/hexagon/qmatmul.h>\n\n"
        + "\n".join(kernels)
    )
    manifest = {
        "schema_version": 1,
        "op": "matmul",
        "example": "llama_cpp_q4_walkthrough",
        "shape": {"M": M, "N": N, "K": K},
        "entries": {name: f"{symbol}_kernel" for name, symbol in SYMBOLS.items()},
        "weight_layout": {
            "llama_source": f"[{NT}][{KT}][576] uint8",
            "dma_staged": f"[{NT}][{KT}][{PADDED_Q4_TILE_BYTES}] uint8",
        },
        "resource_owner": {
            "vtcm": "llama.cpp",
            "dma": "llama.cpp",
            "workers": "llama.cpp",
            "hmx_protocol": "generated compute stage",
        },
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    source_path = output_dir / "kernel_walkthrough_q4_m32_n256_k2048.cc"
    manifest_path = output_dir / "kernel_walkthrough_q4_m32_n256_k2048.json"
    source_path.write_text(source, encoding="utf-8")
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return source_path, manifest_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "generated",
    )
    args = parser.parse_args()
    source, manifest = generate(args.output_dir)
    print(f"generated: {source}")
    print(f"manifest : {manifest}")
    for role, symbol in SYMBOLS.items():
        print(f"  {role:7s} -> {symbol}_kernel")


if __name__ == "__main__":
    main()
